naver:
  openapi:
    movieUrl: https://openapi.naver.com/v1/search/movie.json
    clientId: RnUST_xBNVvRRuGbiDkq
    clientSecret: eI5wkgmJ84

http:
  client:
    maxConnTotal: 50
    maxConnPerRoute: 10
    connectTimeout: 3000
    readTimeout: 5000
